# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
     - 'Img/*.jpg'
     - 'Img/*.png'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: main
      - run: |
          cd main
          ls -a
      - name: get add Pic
        uses: jitterbit/get-changed-files@v1
        id: get-changed-file
      - name: convert pic to webp
        if: (!${{ steps.get-changed-file.outputs.added_modified }})
        run: |
         # sudo apt-get update
          sudo apt-get install webp
          for added_modified_file in ${{ steps.get-changed-file.outputs.added_modified }}; do
            cwebp ./${added_modified_file} -o ./${added_modified_file}.webp
          done
      - name: remove webp
        if: (!${{ steps.get-changed-file.outputs.added_modified }})
        run: |
          for removed_file in ${{ steps.get-changed-file.outputs.removed }}; do
            rm -rf ${removed_file}
          done
      - name: clear jpg png
        run: |
          rm -rf ./Img/*.jpg
          rm -rf ./Img/*.png
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: Webp
          path: Webp
      - run: |
          cp -rf ./Img ../Webp/
          cd ../Webp/Img
          ls -a
      - name: commit
        if: (! ${{ steps.get-changed-file.outputs.added_modified }} || ! ${{ steps.get-changed-file.outputs.removed }})
        run: |
          git config --global user.email superzombies09@gmail.com
          git config --global user.name BoundlessLearning
          git add .
          git commit -m "update" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PICUPDATE_KEY }}
          branch: Webp
      
      
